// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSiteStartNet2023.Data;

#nullable disable

namespace WebSiteStartNet2023.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208224315_seedLocalidades")]
    partial class seedLocalidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRubroCliente")
                        .HasColumnType("int");

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("VisibleEnHome")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdRubroCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeléfonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeléfonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.ExperienciaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExperienciasTrabajo");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.IdiomaPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdiomaId")
                        .HasColumnType("int");

                    b.Property<int>("NivelEscrituraId")
                        .HasColumnType("int");

                    b.Property<int>("NivelLecturaId")
                        .HasColumnType("int");

                    b.Property<int>("NivelOralId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("NivelEscrituraId");

                    b.HasIndex("NivelLecturaId");

                    b.HasIndex("NivelOralId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("IdiomasPostulantes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoPostal = "1900",
                            Nombre = "La Plata",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CodigoPostal = "7600",
                            Nombre = "Mar del Plata",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CodigoPostal = "8000",
                            Nombre = "Bahía Blanca",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 4,
                            CodigoPostal = "7000",
                            Nombre = "Tandil",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CodigoPostal = "1642",
                            Nombre = "San Isidro",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 6,
                            CodigoPostal = "4700",
                            Nombre = "San Fernando del Valle",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 7,
                            CodigoPostal = "4750",
                            Nombre = "Belén",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 8,
                            CodigoPostal = "4740",
                            Nombre = "Andalgalá",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 9,
                            CodigoPostal = "5340",
                            Nombre = "Tinogasta",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 10,
                            CodigoPostal = "4715",
                            Nombre = "Recreo",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 11,
                            CodigoPostal = "3500",
                            Nombre = "Resistencia",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 12,
                            CodigoPostal = "3700",
                            Nombre = "Presidencia Roque Sáenz Peña",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 13,
                            CodigoPostal = "3540",
                            Nombre = "Villa Ángela",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 14,
                            CodigoPostal = "3730",
                            Nombre = "Charata",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 15,
                            CodigoPostal = "3509",
                            Nombre = "General San Martín",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 16,
                            CodigoPostal = "9103",
                            Nombre = "Rawson",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 17,
                            CodigoPostal = "9100",
                            Nombre = "Trelew",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 18,
                            CodigoPostal = "9120",
                            Nombre = "Puerto Madryn",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 19,
                            CodigoPostal = "9000",
                            Nombre = "Comodoro Rivadavia",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 20,
                            CodigoPostal = "9200",
                            Nombre = "Esquel",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 21,
                            CodigoPostal = "5000",
                            Nombre = "Córdoba Capital",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 22,
                            CodigoPostal = "5152",
                            Nombre = "Villa Carlos Paz",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 23,
                            CodigoPostal = "5800",
                            Nombre = "Río Cuarto",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 24,
                            CodigoPostal = "2400",
                            Nombre = "San Francisco",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 25,
                            CodigoPostal = "5900",
                            Nombre = "Villa María",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 26,
                            CodigoPostal = "3400",
                            Nombre = "Corrientes Capital",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 27,
                            CodigoPostal = "3450",
                            Nombre = "Goya",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 28,
                            CodigoPostal = "3230",
                            Nombre = "Paso de los Libres",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 29,
                            CodigoPostal = "3470",
                            Nombre = "Mercedes",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 30,
                            CodigoPostal = "3302",
                            Nombre = "Ituzaingó",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 31,
                            CodigoPostal = "3100",
                            Nombre = "Paraná",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 32,
                            CodigoPostal = "3200",
                            Nombre = "Concordia",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 33,
                            CodigoPostal = "2820",
                            Nombre = "Gualeguaychú",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 34,
                            CodigoPostal = "3260",
                            Nombre = "Concepción del Uruguay",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 35,
                            CodigoPostal = "3153",
                            Nombre = "Victoria",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 36,
                            CodigoPostal = "3600",
                            Nombre = "Formosa Capital",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 37,
                            CodigoPostal = "3610",
                            Nombre = "Clorinda",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 38,
                            CodigoPostal = "3620",
                            Nombre = "Pirané",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 39,
                            CodigoPostal = "3630",
                            Nombre = "Las Lomitas",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 40,
                            CodigoPostal = "3603",
                            Nombre = "El Colorado",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 41,
                            CodigoPostal = "4600",
                            Nombre = "San Salvador de Jujuy",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 42,
                            CodigoPostal = "4612",
                            Nombre = "Palpalá",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 43,
                            CodigoPostal = "4608",
                            Nombre = "Perico",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 44,
                            CodigoPostal = "4512",
                            Nombre = "Libertador General San Martín",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 45,
                            CodigoPostal = "4650",
                            Nombre = "La Quiaca",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 46,
                            CodigoPostal = "6300",
                            Nombre = "Santa Rosa",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 47,
                            CodigoPostal = "6360",
                            Nombre = "General Pico",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 48,
                            CodigoPostal = "6303",
                            Nombre = "Toay",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 49,
                            CodigoPostal = "6200",
                            Nombre = "Realicó",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 50,
                            CodigoPostal = "6319",
                            Nombre = "Victorica",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 51,
                            CodigoPostal = "5300",
                            Nombre = "La Rioja Capital",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 52,
                            CodigoPostal = "5360",
                            Nombre = "Chilecito",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 53,
                            CodigoPostal = "5310",
                            Nombre = "Aimogasta",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 54,
                            CodigoPostal = "5380",
                            Nombre = "Chamical",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 55,
                            CodigoPostal = "5470",
                            Nombre = "Chepes",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 56,
                            CodigoPostal = "5500",
                            Nombre = "Mendoza Capital",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 57,
                            CodigoPostal = "5600",
                            Nombre = "San Rafael",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 58,
                            CodigoPostal = "5501",
                            Nombre = "Godoy Cruz",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 59,
                            CodigoPostal = "5515",
                            Nombre = "Maipú",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 60,
                            CodigoPostal = "5507",
                            Nombre = "Luján de Cuyo",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 61,
                            CodigoPostal = "3300",
                            Nombre = "Posadas",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 62,
                            CodigoPostal = "3360",
                            Nombre = "Oberá",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 63,
                            CodigoPostal = "3380",
                            Nombre = "Eldorado",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 64,
                            CodigoPostal = "3370",
                            Nombre = "Puerto Iguazú",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 65,
                            CodigoPostal = "3350",
                            Nombre = "Apóstoles",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 66,
                            CodigoPostal = "8300",
                            Nombre = "Neuquén Capital",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 67,
                            CodigoPostal = "8370",
                            Nombre = "San Martín de los Andes",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 68,
                            CodigoPostal = "8407",
                            Nombre = "Villa La Angostura",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 69,
                            CodigoPostal = "8322",
                            Nombre = "Cutral Có",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 70,
                            CodigoPostal = "8340",
                            Nombre = "Zapala",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 71,
                            CodigoPostal = "8500",
                            Nombre = "Viedma",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 72,
                            CodigoPostal = "8400",
                            Nombre = "San Carlos de Bariloche",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 73,
                            CodigoPostal = "8332",
                            Nombre = "General Roca",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 74,
                            CodigoPostal = "8324",
                            Nombre = "Cipolletti",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 75,
                            CodigoPostal = "8336",
                            Nombre = "Villa Regina",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 76,
                            CodigoPostal = "4400",
                            Nombre = "Salta Capital",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 77,
                            CodigoPostal = "4560",
                            Nombre = "Tartagal",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 78,
                            CodigoPostal = "4530",
                            Nombre = "Orán",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 79,
                            CodigoPostal = "4440",
                            Nombre = "Metán",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 80,
                            CodigoPostal = "4427",
                            Nombre = "Cafayate",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 81,
                            CodigoPostal = "5400",
                            Nombre = "San Juan Capital",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 82,
                            CodigoPostal = "5425",
                            Nombre = "Rawson",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 83,
                            CodigoPostal = "5407",
                            Nombre = "Rivadavia",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 84,
                            CodigoPostal = "5429",
                            Nombre = "Pocito",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 85,
                            CodigoPostal = "5442",
                            Nombre = "Caucete",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 86,
                            CodigoPostal = "5700",
                            Nombre = "San Luis Capital",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 87,
                            CodigoPostal = "5730",
                            Nombre = "Villa Mercedes",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 88,
                            CodigoPostal = "5881",
                            Nombre = "Merlo",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 89,
                            CodigoPostal = "5710",
                            Nombre = "La Punta",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 90,
                            CodigoPostal = "5711",
                            Nombre = "Quines",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 91,
                            CodigoPostal = "9400",
                            Nombre = "Río Gallegos",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 92,
                            CodigoPostal = "9011",
                            Nombre = "Caleta Olivia",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 93,
                            CodigoPostal = "9405",
                            Nombre = "El Calafate",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 94,
                            CodigoPostal = "9050",
                            Nombre = "Puerto Deseado",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 95,
                            CodigoPostal = "9015",
                            Nombre = "Pico Truncado",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 96,
                            CodigoPostal = "2000",
                            Nombre = "Rosario",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 97,
                            CodigoPostal = "3000",
                            Nombre = "Santa Fe Capital",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 98,
                            CodigoPostal = "2300",
                            Nombre = "Rafaela",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 99,
                            CodigoPostal = "2600",
                            Nombre = "Venado Tuerto",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 100,
                            CodigoPostal = "3560",
                            Nombre = "Reconquista",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 101,
                            CodigoPostal = "4200",
                            Nombre = "Santiago del Estero Capital",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 102,
                            CodigoPostal = "4300",
                            Nombre = "La Banda",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 103,
                            CodigoPostal = "4220",
                            Nombre = "Termas de Río Hondo",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 104,
                            CodigoPostal = "3760",
                            Nombre = "Añatuya",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 105,
                            CodigoPostal = "4230",
                            Nombre = "Frías",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 106,
                            CodigoPostal = "9410",
                            Nombre = "Ushuaia",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 107,
                            CodigoPostal = "9420",
                            Nombre = "Río Grande",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 108,
                            CodigoPostal = "9421",
                            Nombre = "Tolhuin",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 109,
                            CodigoPostal = "9425",
                            Nombre = "San Sebastián",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 110,
                            CodigoPostal = "9412",
                            Nombre = "Lago Escondido",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 111,
                            CodigoPostal = "4000",
                            Nombre = "San Miguel de Tucumán",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 112,
                            CodigoPostal = "4107",
                            Nombre = "Yerba Buena",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 113,
                            CodigoPostal = "4103",
                            Nombre = "Tafí Viejo",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 114,
                            CodigoPostal = "4146",
                            Nombre = "Concepción",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 115,
                            CodigoPostal = "4142",
                            Nombre = "Monteros",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 116,
                            CodigoPostal = "1425",
                            Nombre = "Palermo",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 117,
                            CodigoPostal = "1113",
                            Nombre = "Recoleta",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 118,
                            CodigoPostal = "1405",
                            Nombre = "Caballito",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 119,
                            CodigoPostal = "1428",
                            Nombre = "Belgrano",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 120,
                            CodigoPostal = "1068",
                            Nombre = "San Telmo",
                            ProvinciaId = 24
                        });
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelesConocimiento");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelEscrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelEscrito");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelLectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelLectura");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelOral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelOral");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Postulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivoCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Postulantes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreHome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSlider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Catamarca"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Chaco"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chubut"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Corrientes"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Entre Ríos"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Formosa"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Jujuy"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "La Pampa"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "La Rioja"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Mendoza"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Misiones"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Neuquén"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Río Negro"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Salta"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "San Juan"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "San Luis"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Santa Cruz"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Santa Fe"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Tierra del Fuego"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Tucumán"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Ciudad Autónoma de Buenos Aires"
                        });
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.PuestoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PuestoTrabajos");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.PuestoTrabajoPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExperienciaTrabajoId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExperienciaTrabajoId");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("PuestoTrabajoId");

                    b.ToTable("PuestosTrabajoPostulantes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.RubroCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RubrosClientes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreHome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSlider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Tecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tecnologias");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.TecnologiaPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<int>("TecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelConocimientoId");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("TecnologiaId");

                    b.ToTable("TecnologiasPostulantes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Cliente", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.RubroCliente", "RubroCliente")
                        .WithMany()
                        .HasForeignKey("IdRubroCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubroCliente");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.IdiomaPostulante", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.Idioma", "Idioma")
                        .WithMany("IdiomaPostulantes")
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.NivelEscrito", "NivelEscritura")
                        .WithMany("IdiomaPostulante")
                        .HasForeignKey("NivelEscrituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.NivelLectura", "NivelLectura")
                        .WithMany("IdiomaPostulante")
                        .HasForeignKey("NivelLecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.NivelOral", "NivelOral")
                        .WithMany("IdiomaPostulante")
                        .HasForeignKey("NivelOralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("NivelEscritura");

                    b.Navigation("NivelLectura");

                    b.Navigation("NivelOral");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Localidad", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.Provincia", "Provincia")
                        .WithMany("Localidad")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Postulante", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.PuestoTrabajoPostulante", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.ExperienciaTrabajo", "ExperienciaTrabajo")
                        .WithMany("PuestoTrabajoPostulantes")
                        .HasForeignKey("ExperienciaTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.PuestoTrabajo", "PuestoTrabajo")
                        .WithMany()
                        .HasForeignKey("PuestoTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienciaTrabajo");

                    b.Navigation("Postulante");

                    b.Navigation("PuestoTrabajo");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.TecnologiaPostulante", b =>
                {
                    b.HasOne("WebSiteStartNet2023.Models.NivelConocimiento", "NivelConocimiento")
                        .WithMany("TecnologiaPostulante")
                        .HasForeignKey("NivelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSiteStartNet2023.Models.Tecnologia", "Tecnologia")
                        .WithMany("TecnologiaPostulantes")
                        .HasForeignKey("TecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelConocimiento");

                    b.Navigation("Postulante");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.ExperienciaTrabajo", b =>
                {
                    b.Navigation("PuestoTrabajoPostulantes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Idioma", b =>
                {
                    b.Navigation("IdiomaPostulantes");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelConocimiento", b =>
                {
                    b.Navigation("TecnologiaPostulante");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelEscrito", b =>
                {
                    b.Navigation("IdiomaPostulante");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelLectura", b =>
                {
                    b.Navigation("IdiomaPostulante");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.NivelOral", b =>
                {
                    b.Navigation("IdiomaPostulante");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Provincia", b =>
                {
                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("WebSiteStartNet2023.Models.Tecnologia", b =>
                {
                    b.Navigation("TecnologiaPostulantes");
                });
#pragma warning restore 612, 618
        }
    }
}
